CREATE TABLE "airingupdates" (
	"alid" integer PRIMARY KEY NOT NULL,
	"userid" integer[] NOT NULL
);
--> statement-breakpoint
CREATE TABLE "anime" (
	"alid" integer PRIMARY KEY NOT NULL,
	"enname" varchar(200) NOT NULL,
	"jpname" varchar(200) NOT NULL,
	"optnames" varchar[] NOT NULL,
	"excludenames" varchar[] NOT NULL,
	"status" varchar(16),
	"next_ep_num" numeric,
	"next_ep_air" integer,
	"last_ep" smallint,
	"ep_extras" numeric[] NOT NULL,
	"imglink" varchar(255),
	"fileid" varchar(100)
);
--> statement-breakpoint
CREATE TABLE "completedanime" (
	"userid" integer PRIMARY KEY NOT NULL,
	"completed" integer[] NOT NULL
);
--> statement-breakpoint
CREATE TABLE "config" (
	"userid" integer PRIMARY KEY NOT NULL,
	"pause_airing_updates" boolean DEFAULT false
);
--> statement-breakpoint
CREATE TABLE "syncupd" (
	"userid" integer NOT NULL,
	"queuenum" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "syncupd_queuenum_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"synctype" varchar(20),
	"anime" varchar(255),
	"epnum" numeric,
	"dltype" varchar(10),
	"xdccdata" varchar[] NOT NULL,
	"torrentdata" varchar(255)
);
--> statement-breakpoint
CREATE TABLE "users" (
	"userid" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_userid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"chatid" bigint,
	"username" varchar(255),
	CONSTRAINT "unique_chatid" UNIQUE("chatid"),
	CONSTRAINT "userid_chatid_unique" UNIQUE("userid","chatid")
);
--> statement-breakpoint
CREATE TABLE "watchedepanime" (
	"userid" integer NOT NULL,
	"alid" integer NOT NULL,
	"ep" numeric[] NOT NULL,
	CONSTRAINT "watchedepanime_userid_alid_pk" PRIMARY KEY("userid","alid"),
	CONSTRAINT "watchedepanime_user_anime_unique" UNIQUE("userid","alid")
);
--> statement-breakpoint
CREATE TABLE "watchinganime" (
	"userid" integer PRIMARY KEY NOT NULL,
	"alid" integer[] NOT NULL
);
--> statement-breakpoint
CREATE TABLE "watchlists" (
	"watchlistid" smallint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "watchlists_watchlistid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 32767 START WITH 1 CACHE 1),
	"watchlist_name" varchar(255),
	"alid" integer[] NOT NULL,
	"generated_by" integer NOT NULL
);
--> statement-breakpoint
ALTER TABLE "airingupdates" ADD CONSTRAINT "airingupdates_alid_anime_alid_fk" FOREIGN KEY ("alid") REFERENCES "public"."anime"("alid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "completedanime" ADD CONSTRAINT "completedanime_userid_users_userid_fk" FOREIGN KEY ("userid") REFERENCES "public"."users"("userid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "config" ADD CONSTRAINT "config_userid_users_userid_fk" FOREIGN KEY ("userid") REFERENCES "public"."users"("userid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "syncupd" ADD CONSTRAINT "syncupd_userid_users_userid_fk" FOREIGN KEY ("userid") REFERENCES "public"."users"("userid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watchedepanime" ADD CONSTRAINT "watchedepanime_userid_users_userid_fk" FOREIGN KEY ("userid") REFERENCES "public"."users"("userid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watchedepanime" ADD CONSTRAINT "watchedepanime_alid_anime_alid_fk" FOREIGN KEY ("alid") REFERENCES "public"."anime"("alid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watchinganime" ADD CONSTRAINT "watchinganime_userid_users_userid_fk" FOREIGN KEY ("userid") REFERENCES "public"."users"("userid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "watchlists" ADD CONSTRAINT "watchlists_generated_by_users_userid_fk" FOREIGN KEY ("generated_by") REFERENCES "public"."users"("userid") ON DELETE cascade ON UPDATE no action;